EVAL_CROP_SIZE: (1024, 512) # (width, height), for unpadding rangescaling and stepscaling
TRAIN_CROP_SIZE: (1024, 512) # (width, height), for unpadding rangescaling and stepscaling
AUG:
    AUG_METHOD: "rangescaling" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (1024, 512) # (width, height), for unpadding
    INF_RESIZE_VALUE: 1024  # for rangescaling
    MAX_RESIZE_VALUE: 1024  # for rangescaling
    MIN_RESIZE_VALUE: 1024  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.5  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True
BATCH_SIZE: 16
DATASET:
    DATA_DIR: "./dataset/phone/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 2
    TEST_FILE_LIST: "dataset/phone/test.txt"
    TRAIN_FILE_LIST: "dataset/phone/train.txt"
    VAL_FILE_LIST: "dataset/phone/val.txt"
    IGNORE_INDEX: 255
    SEPARATOR: " "
FREEZE:
    MODEL_FILENAME: "model"
    PARAMS_FILENAME: "params"
MODEL:
    DEFAULT_NORM_TYPE: "bn"
    MODEL_NAME: "deeplabv3p"
    DEEPLAB:
        BACKBONE: "mobilenetv2"
        ASPP_WITH_SEP_CONV: True
        DECODER_USE_SEP_CONV: True
        ENCODER_WITH_ASPP: False
        ENABLE_DECODER: False
TRAIN:
    PRETRAINED_MODEL_DIR: u"pretrained_model/deeplabv3p_mobilenetv2-1-0_bn_coco"
    MODEL_SAVE_DIR: "saved_model/deeplabv3p_mobilenetv2_cityscapes"
    SNAPSHOT_EPOCH: 10
    SYNC_BATCH_NORM: True
TEST:
    TEST_MODEL: "saved_model/deeplabv3p_mobilenetv2_cityscapes/best_model"
SOLVER:
    LOSS: ['dice_loss','bce_loss']
    LR: 0.01
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    NUM_EPOCHS: 400
